" Colors
colo black
"colo dark
"colo blue
"colo macvim

" Scrolling
set guioptions-=l
set guioptions-=r
set guioptions-=L
set guioptions-=R
set guioptions-=T

" Completion
inoremap <C-space> <C-x><C-o>

" Other
set visualbell t_vb=

" Leaders
nmap <leader>u :GundoToggle<cr>
nmap <leader>r :ruby @finder = nil<cr>
nmap <leader>t :FuzzyFinderTextMate<cr>

" FuzzyFinder
let g:fuzzy_ignore='*.png;*.jpg;*.gif;*bmp;*.o;*.class;*.sassc'

" Highlight word under cursor
set updatetime=500
hi CursorToken guibg=#242424
autocmd CursorHold * silent! exe printf('match CursorToken /\<%s\>/', escape(expand('<cword>'), '\'))
autocmd CursorMoved * match none

" Open in fullscreen
"if has("gui_running")
"  set fuoptions=maxvert,maxhorz
"  au GUIEnter * set fullscreen
"endif
