---
- name: stat files
  with_dict: "{{ files }}"
  stat: >
    path="{{ home }}/{{ item.value or '.' + item.key }}"
    follow=no
  register: files_stat

- name: backup files
  with_items: "{{ files_stat.results }}"
  when: item.stat.exists and not item.stat.islnk
  command: mv "{{ item.stat.path }}" "{{ base }}/backups/{{ item.item.key }}.{{ ansible_date_time.epoch }}"

- name: link files
  with_dict: "{{ files }}"
  file: >
    src="{{ base }}/files/{{ item.key }}"
    path="{{ home }}/{{ item.value or '.' + item.key }}"
    state=link

- name: set visibility
  with_dict: "{{ visibility }}"
  command: chflags -h {{ item.value }} "{{ home }}/{{ item.key }}"
