---
- name: Stat dotfiles to determine if they need backing up
  stat:
    path: "{{ home }}/{{ item.value | default('.' + item.key, true) }}"
    follow: false
  loop: "{{ files | dict2items }}"
  register: files_stat

- name: Backup existing files that are not symlinks
  command: >
    mv "{{ item.stat.path }}" "{{ base }}/backups/{{ item.item.key }}.{{ ansible_date_time.epoch }}"
  loop: "{{ files_stat.results }}"
  when:
    - item.stat.exists
    - not item.stat.islnk

- name: Link dotfiles into home directory
  file:
    src: "{{ base }}/files/{{ item.key }}"
    path: "{{ home }}/{{ item.value | default('.' + item.key, true) }}"
    state: link
  loop: "{{ files | dict2items }}"

- name: Set visibility for specified files
  command: chflags -h {{ item.value }} "{{ home }}/{{ item.key }}"
  loop: "{{ visibility | dict2items }}"
