---
- name: Set macOS preferences
  shell: "{{ item }}"
  loop: "{{ preferences }}"

- name: Restart relevant macOS services
  command: killall {{ item }}
  loop:
    - Dock
    - Finder
    - SystemUIServer
