---
- name: Clone Vundle
  ansible.builtin.git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ home }}/.vim/bundle/Vundle.vim"
    clone: yes
    update: yes  # optional: ensures latest version if already cloned

- name: Install Vim plugins via Vundle
  ansible.builtin.command: vim +PluginInstall +qall
